const REGISTER_MODAL = 'Jolly/App/REGISTER_MODAL';
const LOGIN_MODAL = 'Jolly/App/LOGIN_MODAL';
const FORGOT_PASSWORD_MODAL = 'Jolly/App/FORGOT_PASSWORD_MODAL';
export default {
  REGISTER_MODAL,
  LOGIN_MODAL,
  FORGOT_PASSWORD_MODAL,
};
