const ROLES = [
  'Art Director',
  'Costume Designer',
  'Fashion Designer',
  'Floral Crew',
  'Floral Designer',
  'Graphic Designer',
  'Lighting Designer',
  'Muralist',
  'Set Designer',
  'Stage Designer',
  'Visual Designer',
  'Aerial Performer',
  'Casino Dealer',
  'Dancer',
  'DJ',
  'Emcee',
  'Entertainer',
  'Juggler',
  'Master of Ceremonies',
  'Musician',
  'Assistant Banquet Manager',
  'Banquet Manager',
  'Barback',
  'Barista',
  'Bartender',
  'Busser',
  'Cake Artist',
  'Caterer',
  'Catering Crew',
  'Chef',
  'Concessions Vendor',
  'Cook',
  'Dishwasher',
  'General Kitchen Staff',
  'Line Cook',
  'Mixologist',
  'Prep Cook',
  'Server',
  'Sous Chef',
  'Concierge',
  'Customer Service',
  'Exhibition Attendant',
  'Front of House',
  'Greeter',
  'Host / Hostess',
  'Registration Desk Attendant',
  'Ticketing Attendant',
  'Usher',
  'Accountant',
  'Art Installer',
  'Babysitter',
  'Child Care Professional',
  'Pet Sitter',
  'Room Monitor',
  'Silent Auction Staff',
  'Sports Official',
  'Volunteer',
  'Volunteer Coordinator',
  'Officiant',
  'Boat Captain',
  'Boat Crew',
  'Cleaning Crew',
  'Construction Crew',
  'Crew Chief',
  'Delivery Driver',
  'Directional Staff',
  'Driver',
  'Event Setup Crew',
  'General Crew',
  'Landscaping Crew',
  'Painter',
  'Parking Attendant',
  'Security Guard',
  'Stocker',
  'Transportation Planner',
  'Waste Management Crew',
  'Event Coordinator',
  'Event Marketing Manager',
  'Event Planner',
  'Event Producer',
  'Event Promoter',
  'Media Relations Manager',
  'Public Relations Manager',
  'Social Media Manager',
  'Staff Director',
  'Publicist',
  'Brand Ambassador',
  'Event Marketer',
  'Merchandise Vendor',
  'Model',
  'Product Promoter',
  'Sales',
  'Visual Merchandiser',
  'Artist Hospitality Manager',
  'Artist Relations',
  'A/V Technician',
  'Assistant Camera Operator',
  'Audio Crew',
  'Audio Post-production',
  'Camera Operator',
  'Director of Photography',
  'Drone Operator',
  'Photographer',
  'Photography Assistant',
  'Photography Crew',
  'Photography Post-production',
  'Photo Retoucher',
  'Production Assistant',
  'Production Assistant',
  'Production Crew',
  'Production Director',
  'Production Manager',
  'Sound Engineer',
  'Sound Mixer',
  'Touring Engineer',
  'Video/Film Crew',
  'Video/Film Post-production',
  'Videographer',
  'Videography Assistant',
  'Communications Technician',
  'Electrician',
  'Equipment Repair Technician',
  'IT & Network Technician',
  'Lighting Operator',
  'Lighting Technician',
  'Stage Manager',
  'Stage Rigger',
  'Tech Support',
  'Zone Manager',
  'Aesthetician',
  'Assistant Stylist',
  'Chiropractor',
  'Hair Stylist',
  'Make-up Artist',
  'Masseuse',
  'Model Prep Crew',
];

export default ROLES;
